### ISSUE TITLE
The library does not compile on MSVC

### ISSUE THREAD

**Issue by alexandrshiriaev** [Sinan-Karakaya/cpp-i18n#7]
`cl : Command line error D8021 : invalid numeric argument '/Wextra'`

**Comment by Sinan-Karakaya** [comment]
Hi, thanks for notifying me, I'm working on fixing it + adding more informations on the README (coming back on old projects... I almost want to remake it from scratch)

**Comment by Sinan-Karakaya** [comment]
Hey @alexandrshiriaev, your problem should be solved with the latest release :) (v0.2.2)

Thanks for telling me, and don't hesitate to open a new issue if needed!
