### ISSUE TITLE
Cannot open include file: 'cpp-i18n/Translator.hpp'

### ISSUE THREAD

**Issue by alexandrshiriaev** [Sinan-Karakaya/cpp-i18n#9]
`#include <cpp-i18n/Translator.hpp>`

```
FetchContent_Declare(
        cpp-i18n
        GIT_REPOSITORY   https://github.com/Sinan-Karakaya/cpp-i18n.git
        GIT_TAG          v0.2.2
)

FetchContent_MakeAvailable(cpp-i18n)

target_link_libraries(${PROJECT_NAME} PUBLIC
        nanoid
        cpp-i18n
        nlohmann_json::nlohmann_json
)
```

> src\main.cpp(6): fatal error C1083: Cannot open include file: 'cpp-i18n/Translator.hpp': No such file or directory
> ninja: build stopped: subcommand failed.

**Comment by Sinan-Karakaya** [comment]
Hi, a fix should have been pushed, you don't need to change anything normally :) Sorry for the trouble, and please close the issue if your problem is solved

**Comment by Sinan-Karakaya** [comment]
Hi, please add this piece of code to your CMakeLists.txt

```cmake
...previous code

target_include_directories(
    ${PROJECT_NAME}
    PRIVATE
    ${cpp-i18n_SOURCE_DIR}/include)
``` 

I will add that step to the README :)
Please close the issue if this resolved your problem

**Comment by alexandrshiriaev** [comment]
Thanks, working!
